name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 11
          - os: windows-latest
            java: 11
          - os: macos-latest
            java: 11
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Scala and JDK 1.${{ matrix.java }}
      uses: olafurpg/setup-scala@v11
      with:
        java-version: "adopt@1.${{ matrix.java }}"
    - name: Generate artifact files
      run: sbt publishLocal
    - name: Run tests
      run: sbt -v +test
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        path: |
          build.sbt
          project/build.properties
          project/plugins.sbt
          target/scala-*/silver_*-SNAPSHOT.jar
          target/scala-*/silver_*-SNAPSHOT-tests.jar
          target/scala-*/silver_*-SNAPSHOT-tests-sources.jar
