name: Run Backend CI

on:
  push:
    branches: [ silver-as-a-submodule ]
  pull_request:
    branches: [ silver-as-a-submodule ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - repo: 'silicon'
          - repo: 'carbon'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout backend
      uses: actions/checkout@v3
      with:
        repository: viperproject/${{ matrix.repo }}
        token: ${{ secrets.PAT }}
        ref: silver-as-a-submodule
        submodules: true

    - name: Checkout current silver
      run: |
        git checkout -b ci-test-${{ github.sha }}
        cd silver
        git fetch origin ${{ github.ref }}
        git checkout ${{ github.sha }}
        cd ..

    - name: Push temporary branch
      run: |
        git config --global user.name 'Silver Bot'
        git config --global user.email 'bot@noreply.github.com'
        git commit -am "Set silver submodule to ${{ github.sha }} [skip ci]"
        git push origin ci-test-${{ github.sha }}

    - name: Run CI
      uses: convictional/trigger-workflow-and-wait@v1.6.0
      with:
        owner: viperproject
        repo: ${{ matrix.repo }}
        github_token: ${{ secrets.PAT }}
        ref: ci-test-${{ github.sha }}
        workflow_file_name: ci.yml

    - name: Delete temporary branch
      if: always()
      run: |
        git push origin --delete ci-test-${{ github.sha }}
