name: Scala CI

on:
  push:
    branches: [ silver-as-a-submodule ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - repo: 'silicon'
          #- repo: 'carbon'
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: viperproject/${{ matrix.repo }}
        token: ${{ secrets.PAT }}
        ref: silver-as-a-submodule
        submodules: true

    - name: Update submodules
      run: |
        git submodule update --remote --recursive

        git config --global user.name 'Silver Bot'
        git config --global user.email 'bot@noreply.github.com'
        git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"
